title: "BlenderFDS"
description: "The open user interface for the NIST Fire Dynamics Simulator (FDS)"
url: "https://firetools.github.io"
baseurl: "/blenderfds.web"

#logo: "/assets/images/icon.png"

#permalink: pretty
exclude: ["LICENSE.txt", "README.md",]

remote_theme: pmarsceill/just-the-docs
color_scheme: "light"  # or a custom scheme that you define

search_enabled: true

aux_links:  # aux links for the upper right corner
  "BlenderFDS on GitHub":
    - "//github.com/firetools/blenderfds"
aux_links_new_tab: false

back_to_top: true
back_to_top_text: "Back to top"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/firetools/blenderfds.web"
gh_edit_branch: "main"
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Google Analytics Tracking (optional)
# ga_tracking: UA-2709176-10
# ga_tracking_anonymize_ip: true  # GDPR compliance
